### ISSUE TITLE
error when i want extract missing strings for xrengine client package

### ISSUE THREAD

**Issue by johnfelipe** [mateussouzaweb/translator#1]
https://github.com/XRFoundation/XREngine/tree/dev/packages/client

	translator \
		--source /root/XREngine/packages/client/ \
		--destination /root/XREngine/packages/client/i18n/en/translation.json

show me this error:

	panic: json: cannot unmarshal object into Go value of type string

	goroutine 1 [running]:
	main.main()
			/home/runner/work/translator/translator/cmd/main.go:75 +0x617

**Comment by mateussouzaweb** [comment]
Hey, pretty cool this Engine!

I made some checks and could see that the structure of this file is organized into nested translations. This project only supports single translations for now, so you need to have something like the sample below to work:

```json
{
    "term.to.translate": "translation"
}
```

Since you are using i18next, you need to extract the translations using their own parsers: https://www.i18next.com/how-to/extracting-translations

I will keep this issue open for a future enhancement.

**Comment by johnfelipe** [comment]
Wich one will be steps for extract to xrengine strings not translated?

Add that variable to Json config?

And use that other repository?

Pls guide me in this matters

**Comment by mateussouzaweb** [comment]
``translator`` is not capable of handling translations with this format yet... 

It is better to use the built-in parsers from i18next:  https://www.i18next.com/how-to/extracting-translations. Please read their docs to know how to use them.

**Comment by johnfelipe** [comment]
https://www.i18next.com/how-to/extracting-translations, extract tsx files?
